# Пропишем версию
version: '3.3'
# Перечислим сервисы
services:
    nginx:
# Пропишем какой образ мы хотим использовать
        image: nginx:latest
# Назовем свой контейнер по красивому
        container_name: nginx
# Проброс портов
        ports:
            - "80:80"
            - "443:443"
# Проброс папок
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www/
            - ./logs:/var/log/nginx/
            - ./html:/usr/share/nginx/html/
# Укажем зависимости
        links:
            - php

    mysql:

        image: mysql:latest

        ports:
            - "3306:3306"

        container_name: mysql
# Пропишем настройки, предлагаю использовать вместо mypassword более сложный пароль, он пренадлежит root
        environment:

            - MYSQL_ROOT_PASSWORD=pgx4or2cv
            - MYSQL_DATABASE=clean
            - MYSQL_USER=zabik
            - MYSQL_PASSWORD=pgx4or2cv


        volumes:
            - ./mysql:/var/lib/mysql


    php:
# Билдим с помощью dockerfile указав директорию где он лежит
        build: ./images/php

        container_name: php-fpm

        volumes:
            - ./www:/var/www

        links:
            - mysql


    phpmyadmin:

        image: phpmyadmin/phpmyadmin

        container_name: phpmyadmin

        ports:

            - 8090:80

        links:
            - mysql:db